### ISSUE TITLE
Hover effect on reset button

### ISSUE THREAD

**Issue by ghost** [Nova281/fortniteClicker#11]
An effect like a darker color background

**Comment by benz-le** [comment]
I have done so but the original cursor shows up instead

**Comment by ghost** [comment]
Revert that commit. All you need is just a `div:first-of-type:hover` style.

For example:

```css
div:first-of-type:hover {
    /* hover changes */
}

**Comment by ghost** [comment]
Looks nice. But after thinking about it, maybe an `:active` effect instead of `:hover`. I'll still close this issue now
